module.exports = {
    v00000: { Beschreibung: "Artikelbezeichnung", Zugriff: "RW", Typ: "char[31]", count: 20, Variable: "v00000", Bemerkung: "W: 0 < strlen < 31", Min: null, Max: null },
    v00001: { Beschreibung: "Best.-Nr.", Zugriff: "RW", Typ: "char[16]", count: 12, Variable: "v00001", Bemerkung: "W: 0 < strlen < 17", Min: null, Max: null },
    v00002: { Beschreibung: "MAC-Adresse Webserver", Zugriff: "R", Typ: "char[18]", count: 13, Variable: "v00002", Bemerkung: "W: 0 < strlen < 17", Min: null, Max: null },
    v00003: { Beschreibung: "Sprache", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v00003", Bemerkung: "WR: „ de”, „ en”, „ fr”, „ sl”", Min: null, Max: null },
    v00004: {
        Beschreibung: "Datum",
        Zugriff: "RW",
        Typ: "char[10]",
        count: 9,
        Variable: "v00004",
        Bemerkung: "R: nach eingestelltem Format („ dd.mm.yy” „ yyyy.mm.dd” „ dd.mm.yyyyy” W: Nur in Format: dd.mm.yy",
        Min: null,
        Max: null,
    },
    v00005: { Beschreibung: "Uhrzeit", Zugriff: "RW", Typ: "char[10]", count: 9, Variable: "v00005", Bemerkung: "R: Format: hh:mm:ss W: Format: hh:mm:ss", Min: null, Max: null },
    v00006: { Beschreibung: "Sommer / Winter", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00006", Bemerkung: "W: „ o”-Aktiv R: 0-Winterzeit, 1 = Sommerzeit", Min: null, Max: null },
    v00007: {
        Beschreibung: "Auto. Softwareupdates erlauben",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v00007",
        Bemerkung: "W: „ o”-Aktiv R: 0-Winterzeit, 1 = aktiviert",
        Min: null,
        Max: null,
    },
    v00008: {
        Beschreibung: "Zugang zum Helios Portal erlauben",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v00008",
        Bemerkung: "W: „ o”-Aktiv R: 0-Winterzeit, 1 = aktiviert",
        Min: null,
        Max: null,
    },
    v00012: { Beschreibung: "Spannung Lüfterstufe 1 Abluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00012", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00013: { Beschreibung: "Spannung Lüfterstufe 1 Zuluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00013", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00014: { Beschreibung: "Spannung Lüfterstufe 2 Abluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00014", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00015: { Beschreibung: "Spannung Lüfterstufe 2 Zuluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00015", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00016: { Beschreibung: "Spannung Lüfterstufe 3 Abluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00016", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00017: { Beschreibung: "Spannung Lüfterstufe 3 Zuluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00017", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00018: { Beschreibung: "Spannung Lüfterstufe 4 Abluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00018", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00019: { Beschreibung: "Spannung Lüfterstufe 4 Zuluft", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00019", Bemerkung: "R: Format = .1f", Min: 1.6, Max: 10 },
    v00020: { Beschreibung: "Min. Lüfterstufe", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00020", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 1 },
    v00020: { Beschreibung: "KWL-BE aktiviert", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00020", Bemerkung: "RW: 0 =Aus 1 = Ein", Min: 0, Max: 1 },
    v00022: { Beschreibung: "KWL-BEC aktiviert", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00022", Bemerkung: "RW: 0 =Aus 1 = Ein", Min: 0, Max: 1 },
    v00023: { Beschreibung: "Gerätekonfiguration", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00023", Bemerkung: "RW: 1-DiBt 2-Passivhaus", Min: 1, Max: 2 },
    v00024: { Beschreibung: "Vorheizung Status", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00024", Bemerkung: "RW: 0 =Aus 1 = Ein", Min: 0, Max: 1 },
    v00025: { Beschreibung: "KWL-FTF konfig 0", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00025", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00026: { Beschreibung: "KWL-FTF konfig 1", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00026", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00027: { Beschreibung: "KWL-FTF konfig 2", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00027", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00028: { Beschreibung: "KWL-FTF konfig 3", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00028", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00029: { Beschreibung: "KWL-FTF konfig 4", Zugriff: "RW", Typ: "char[10]", count: 5, Variable: "v00029", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00030: { Beschreibung: "KWL-FTF konfig 5", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00030", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00031: { Beschreibung: "KWL-FTF konfig 6", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00031", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 1, Max: 3 },
    v00032: { Beschreibung: "KWL-FTF konfig 7", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00032", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 0, Max: 2 },
    v00033: { Beschreibung: "Feuchte-Steuerung Status", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00033", Bemerkung: "RW: 1=RF, 2=Temp., 3=kombiniert", Min: 0, Max: 2 },
    v00034: { Beschreibung: "Feuchte-Steuerung Sollwert", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v00034", Bemerkung: "RW: in Prozent", Min: 20, Max: 80 },
    v00035: { Beschreibung: "Feuchte-Steuerung Stufen", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v00035", Bemerkung: "RW: in Prozent", Min: 5, Max: 20 },
    v00036: { Beschreibung: "Feuchte-Steuerung Stoppzeit", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v00036", Bemerkung: "RW: in Stunden", Min: 0, Max: 24 },
    v00037: { Beschreibung: "CO2-Steuerung Status", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00037", Bemerkung: "RW: 0=Aus, 2 = Stufig., 3 = Stufenlos", Min: 0, Max: 2 },
    v00038: { Beschreibung: "CO2-Steuerung Sollwert", Zugriff: "RW", Typ: "char[4]", count: 6, Variable: "v00038", Bemerkung: "RW: in ppm", Min: 300, Max: 5000 },
    v00039: { Beschreibung: "CO2-Steuerung Stufen", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00039", Bemerkung: "RW: in ppm", Min: 50, Max: 400 },
    v00040: { Beschreibung: "VOC-Steuerung Status", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00040", Bemerkung: "RW: 0=Aus, 2 = Stufig., 3 = Stufenlos", Min: 0, Max: 2 },
    v00041: { Beschreibung: "VOC-Steuerung Sollwert", Zugriff: "RW", Typ: "char[4]", count: 6, Variable: "v00041", Bemerkung: "RW: in ppm", Min: 300, Max: 5000 },
    v00042: { Beschreibung: "VOC-Steuerung Stufen", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00042", Bemerkung: "RW: in ppm", Min: 50, Max: 400 },
    v00043: { Beschreibung: "Behaglichkeits- temperatur", Zugriff: "RW", Typ: "char[4]", count: 6, Variable: "v00043", Bemerkung: "R: Format = .1f", Min: 10, Max: 25 },
    v00051: { Beschreibung: "Zeitzone Abweichung von GMT", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00051", Bemerkung: "RW: Zeitzonen", Min: 0, Max: 14 },
    v00052: { Beschreibung: "Datumsformat", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00052", Bemerkung: "R: 0 = „ dd.mm.yy”, 1 = „ mm.dd.yyyy”, 2 = „ yyyyy.mm.dd”", Min: 0, Max: 2 },
    v00053: { Beschreibung: "Wärmetauscher Typ", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00053", Bemerkung: "RW: 1 = „ Kunststoff” 2 = „ Aluminium” 3 = „ Enthalpie”", Min: 1, Max: 3 },
    v00091: { Beschreibung: "Partybetrieb Dauer", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00091", Bemerkung: "RW: in Minuten", Min: 5, Max: 180 },
    v00092: { Beschreibung: "Partybetrieb Lüfterstufe", Zugriff: "RW", Typ: "char[3]", count: 5, Variable: "v00092", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v00093: { Beschreibung: "Partybetrieb Restzeit", Zugriff: "R", Typ: "char[3]", count: 6, Variable: "v00093", Bemerkung: "RW: in Minuten", Min: 0, Max: 180 },
    v00094: { Beschreibung: "Partybetrieb aktivieren / abrechen", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00094", Bemerkung: "RW: 0 = Aus 1 = Ein", Min: 0, Max: 1 },
    v00096: { Beschreibung: "Ruhebetrieb Dauer", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00096", Bemerkung: "RW: in Minuten", Min: 5, Max: 180 },
    v00097: { Beschreibung: "Ruhebetrieb Lüfterstufe", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00097", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v00098: { Beschreibung: "Ruhebetrieb Restzeit", Zugriff: "R", Typ: "char[3]", count: 6, Variable: "v00098", Bemerkung: "R: in Minuten", Min: 0, Max: 180 },
    v00099: { Beschreibung: "Ruhebetrieb aktivieren / abbrechen", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00099", Bemerkung: "RW: 0 = Aus 1 = Ein", Min: 0, Max: 1 },
    v00101: { Beschreibung: "Betriebsart", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00101", Bemerkung: "R: 0 = Automat. 1 = Handbetrieb W: 0 = Automat. 1 = Handbetrieb", Min: 0, Max: 1 },
    v00102: { Beschreibung: "Lüfterstufe", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00102", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v00103: { Beschreibung: "Prozentuale Lüfterstufe", Zugriff: "R", Typ: "char[3]", count: 6, Variable: "v00103", Bemerkung: "R: prozentuale Lüfteransteuerung", Min: 0, Max: 100 },
    v00104: { Beschreibung: "Temperatur Außenluft", Zugriff: "R", Typ: "char[7]", count: 8, Variable: "v00104", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: -27, Max: 9998 },
    v00105: { Beschreibung: "Temperatur Zuluft", Zugriff: "R", Typ: "char[7]", count: 8, Variable: "v00105", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: -27, Max: 9998 },
    v00106: { Beschreibung: "Temperatur Fortluft", Zugriff: "R", Typ: "char[7]", count: 8, Variable: "v00106", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: -27, Max: 9998 },
    v00107: { Beschreibung: "Temperatur Abluft", Zugriff: "R", Typ: "char[7]", count: 8, Variable: "v00107", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: -27, Max: 9998 },
    v00108: {
        Beschreibung: "VHZ Kanalfühler (-Außenluft- T5)",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00108",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00110: {
        Beschreibung: "NHZ Rücklauffühler (-Warmwasser-Register- T7)",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00110",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00111: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 1", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00111", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00112: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 2", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00112", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00113: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 3", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00113", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00114: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 4", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00114", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00115: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 5", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00115", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00116: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 16", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00116", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00117: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 7", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00117", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00118: { Beschreibung: "Externer Fühler KWL-FTF Feuchte 8", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00118", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00119: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 1",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00119",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00120: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 2",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00120",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00121: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 3",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00121",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00122: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 4",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00122",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00123: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 5",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00123",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00124: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 6",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00124",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00125: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 7",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00125",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00126: {
        Beschreibung: "Externer Fühler KWL-FTF Temp 8",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00126",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00128: { Beschreibung: "Externer Fühler KWL-CO2 1", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00128", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00129: { Beschreibung: "Externer Fühler KWL-CO2 2", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00129", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00130: { Beschreibung: "Externer Fühler KWL-CO2 3", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00130", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00131: { Beschreibung: "Externer Fühler KWL-CO2 4", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00131", Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00132: { Beschreibung: "Externer Fühler KWL-CO2 5", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00132", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00133: { Beschreibung: "Externer Fühler KWL-CO2 6", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00133", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00134: { Beschreibung: "Externer Fühler KWL-CO2 7", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00134", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00135: { Beschreibung: "Externer Fühler KWL-CO2 8", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00135", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00136: { Beschreibung: "Externer Fühler KWL-VOC 1", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00136", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00137: { Beschreibung: "Externer Fühler KWL-VOC 2", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00137", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00138: { Beschreibung: "Externer Fühler KWL-VOC 3", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00138", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00139: { Beschreibung: "Externer Fühler KWL-VOC 4", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00139", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00140: { Beschreibung: "Externer Fühler KWL-VOC 5", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00140", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00141: { Beschreibung: "Externer Fühler KWL-VOC 6", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00141", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00142: { Beschreibung: "Externer Fühler KWL-VOC 7", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00142", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00143: { Beschreibung: "Externer Fühler KWL-VOC 8", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00143", Bemerkung: "R: Wenn val >=9999 dann „ -”", Min: 0, Max: 9998 },
    v00146: {
        Beschreibung: "NHZ Kanalfühler (-Zuluft- T6)",
        Zugriff: "R",
        Typ: "char[7]",
        count: 8,
        Variable: "v00146",
        Bemerkung: "R: Format = .1f. Wenn val >=9999 dann „ -”",
        Min: -27,
        Max: 9998,
    },
    v00201: {
        Beschreibung: "Wochenprofil NHZ",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v00201",
        Bemerkung: "RW: Wert für die Variablen: v00230..v00259 (y) 0 = Standard 1; 1 = Standard 2; 2 = Festwert; 3 = Individuell 1; 4 = Individuell 2; 5 = NA; 6 = Aus",
        Min: 0,
        Max: 6,
    },
    v00303: { Beschreibung: "Ser. Nr.", Zugriff: "RW", Typ: "char[16]", count: 12, Variable: "v00303", Bemerkung: "W: 0 < strlen > 16", Min: null, Max: null },
    v00304: { Beschreibung: "ProdCode", Zugriff: "RW", Typ: "char[13]", count: 11, Variable: "v00304", Bemerkung: "W: 0 < strlen > 13", Min: null, Max: null },
    v00348: { Beschreibung: "Zuluft rpm", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00348", Bemerkung: "R: min -1", Min: 0, Max: 9999 },
    v00349: { Beschreibung: "Abluft rpm", Zugriff: "R", Typ: "char[4]", count: 6, Variable: "v00349", Bemerkung: "R: min -1", Min: 0, Max: 9999 },
    v00403: { Beschreibung: "Logout", Zugriff: "W", Typ: "char[1]", count: 5, Variable: "v00403", Bemerkung: "W: Logout", Min: 1, Max: 1 },
    v00601: { Beschreibung: "Urlaubsprogramm", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00601", Bemerkung: "RW: 0-Aus; 1-Intervall; 2-Konstant", Min: 0, Max: 2 },
    v00602: { Beschreibung: "Lüfterstufe Urlaubsprogramm", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v00602", Bemerkung: "RW: Lüfterstufe", Min: 1, Max: 4 },
    v00603: {
        Beschreibung: "Start",
        Zugriff: "RW",
        Typ: "char[10]",
        count: 9,
        Variable: "v00603",
        Bemerkung: "RW: nach eingestelltem Format („ dd.mm.yy” „ yyyy.mm.dd” „ dd.mm.yyyyy”",
        Min: null,
        Max: null,
    },
    v00604: {
        Beschreibung: "Ende",
        Zugriff: "RW",
        Typ: "char[10]",
        count: 9,
        Variable: "v00604",
        Bemerkung: "RW: nach eingestelltem Format („ dd.mm.yy” „ yyyy.mm.dd” „ dd.mm.yyyyy”",
        Min: null,
        Max: null,
    },
    v00605: { Beschreibung: "Intervall", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v00605", Bemerkung: "RW: Zeit in Stunden", Min: 1, Max: 24 },
    v00606: { Beschreibung: "Einschaltzeit", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v00606", Bemerkung: "RW: in Minuten", Min: 5, Max: 300 },
    v01010: {
        Beschreibung: "VHZ Typ",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v01010",
        Bemerkung: "RW: 1 = EH-Basis; 2 = EH- ERW; 3 = SEWT; 4 = 1-Intervall; 2-Konstant",
        Min: 1,
        Max: 4,
    },
    v01017: {
        Beschreibung: "Funktionsart KWL-EM (Zuordnungen Relais auf Klappen / Störausgänge)",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v01017",
        Bemerkung: "RW: 1 = Funktion 1, 2 = Funktion 2",
        Min: 1,
        Max: 2,
    },
    v01019: { Beschreibung: "Nachlaufzeit VHZ / NHZ", Zugriff: "RW", Typ: "char[3]", count: 6, Variable: "v01019", Bemerkung: "RW: Nachlaufzeit in Sek.", Min: 60, Max: 120 },
    v01020: { Beschreibung: "Externer Kontakt", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01020", Bemerkung: "RW: 1 = Funktion 1; 2 = Funktion 2; 3 = Funktion 3; ...", Min: 1, Max: 6 },
    v01021: {
        Beschreibung: "Störausgangsfunktion: Sammelstörung oder nur Fehler",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v01021",
        Bemerkung: "RW: 1 = Sammelstörung; 2 = Nur Fehler 2",
        Min: 1,
        Max: 2,
    },
    v01031: { Beschreibung: "Filterwechsel", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01031", Bemerkung: "RW: 0 = Nein 1 = Ja", Min: 0, Max: 1 },
    v01032: { Beschreibung: "Wechselintervall", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v01032", Bemerkung: "RW: Wechsleintervall in Monaten", Min: 0, Max: 12 },
    v01033: { Beschreibung: "Restlaufzeit", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01033", Bemerkung: "RW: in Minuten", Min: 0, Max: 4294967295 },
    v01035: { Beschreibung: "Bypass Raum/Temp.", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v01035", Bemerkung: "RW: in °C", Min: 10, Max: 40 },
    v01036: { Beschreibung: "Bypass Min. Außentemp.", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v01036", Bemerkung: "RW: in °C", Min: 5, Max: 20 },
    v01037: { Beschreibung: "Offset Zulufttemperatur", Zugriff: "RW", Typ: "char[2]", count: 5, Variable: "v01037", Bemerkung: "RW: in °C", Min: 3, Max: 10 },
    v01041: { Beschreibung: "Auslieferzustand WZU", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01041", Bemerkung: "W: 1 = Reset der individuellen Schaltzeiten", Min: 0, Max: 1 },
    v01042: { Beschreibung: "Werksreset", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01042", Bemerkung: "W: 1 = Reset Start", Min: 0, Max: 1 },
    v01050: { Beschreibung: "Zuluft", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01050", Bemerkung: "RW: Lüfterstufe", Min: 1, Max: 4 },
    v01051: { Beschreibung: "Abluft", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01051", Bemerkung: "RW: Lüfterstufe", Min: 1, Max: 4 },
    v01061: { Beschreibung: "Zuordnung Lüfterstufen (bei stufig) Bereich 0-2", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01061", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 2 },
    v01062: { Beschreibung: "Zuordnung Lüfterstufen (bei stufig) Bereich 2-4", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01062", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v01063: { Beschreibung: "Zuodnung Lüfterstufen (bei stufig) Bereich 4-6", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01063", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v01064: { Beschreibung: "Zuodnung Lüfterstufen (bei stufig) Bereich 6-8", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01064", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v01065: { Beschreibung: "Zuodnung Lüfterstufen (bei stufig) Bereich 8-10", Zugriff: "RW", Typ: "char[10]", count: 5, Variable: "v01065", Bemerkung: "RW: Lüfterstufe", Min: 0, Max: 4 },
    v01066: { Beschreibung: "Offset Abluft", Zugriff: "RW", Typ: "char[10]", count: 9, Variable: "v01066", Bemerkung: "RW: (Float_Value)", Min: null, Max: null },
    v01068: { Beschreibung: "Zuodnung Lüfterstufen Stufig oder 0-10 Volt", Zugriff: "RW", Typ: "char[1]", count: 5, Variable: "v01068", Bemerkung: "W: 0 = 0...10V; 1 = Stufig", Min: 0, Max: 1 },
    v01071: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01071", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01072: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01072", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01073: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01073", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01074: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01074", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01075: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01075", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01076: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01076", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01077: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01077", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01078: { Beschreibung: "Sensorname Feuchte und Temp.", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01078", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01081: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01081", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01082: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01082", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01083: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01083", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01084: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01084", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01085: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01085", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01086: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01086", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01087: { Beschreibung: "Sensorname CO2", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01087", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01088: { Beschreibung: "Sensorname CO2", Zugriff: "R", Typ: "char[15]", count: 12, Variable: "v01088", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01091: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01091", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01092: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01092", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01093: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01093", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01094: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01094", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01095: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01095", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01096: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01096", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01097: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01097", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01098: { Beschreibung: "Sensorname VOC", Zugriff: "RW", Typ: "char[15]", count: 12, Variable: "v01098", Bemerkung: "W: 0 < strlen > 15", Min: null, Max: null },
    v01101: { Beschreibung: "Software Version Basis", Zugriff: "R", Typ: "char[5]", count: 7, Variable: "v01101", Bemerkung: 'R: Format "xx.xx"', Min: 0, Max: 99.99 },
    v01103: { Beschreibung: "Betr. Stdn. Zuluft Vent.", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01103", Bemerkung: "in Minuten", Min: 0, Max: 4294967295 },
    v01104: { Beschreibung: "Betr. Stdn. Abluft Vent.", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01104", Bemerkung: "in Minuten", Min: 0, Max: 4294967295 },
    v01105: { Beschreibung: "Betr. Stdn. VHZ", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01105", Bemerkung: "in Minuten", Min: 0, Max: 4294967295 },
    v01106: { Beschreibung: "Betr. Stdn. NHZ", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01106", Bemerkung: "in Minuten", Min: 0, Max: 4294967295 },
    v01108: { Beschreibung: "Abgegebene Leistung VHZ in %", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01108", Bemerkung: "Wert/100", Min: 0, Max: 4294967295 },
    v01109: { Beschreibung: "Abgegebene Leistung NHZ in %", Zugriff: "R", Typ: "char[10]", count: 9, Variable: "v01109", Bemerkung: "Wert/100", Min: 0, Max: 4294967295 },
    v01120: { Beschreibung: "Reset Flag", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v01120", Bemerkung: "W: 1 = Reset Flag", Min: 1, Max: 1 },
    v01123: {
        Beschreibung: "Fehler",
        Zugriff: "R",
        Typ: "char[10]",
        count: 9,
        Variable: "v01123",
        Bemerkung: 'R: Fehler als Int-Wert  (siehe Ta- belle "codierung") Beachte: V01303 - V01306',
        Min: 0,
        Max: 4294967295,
    },
    v01124: {
        Beschreibung: "Warnungen",
        Zugriff: "R",
        Typ: "char[3]",
        count: 6,
        Variable: "v01124",
        Bemerkung: 'R: Warnungen als Int-Wert (siehe Tabelle "codierung") Beachte: V01303 - V01306',
        Min: 0,
        Max: 255,
    },
    v01125: {
        Beschreibung: "Infos",
        Zugriff: "R",
        Typ: "char[3]",
        count: 6,
        Variable: "v01125",
        Bemerkung: 'R: Infos als Int-Wert (siehe Tabelle "codierung") Beachte: V01303 - V01306',
        Min: 0,
        Max: 255,
    },
    v01300: { Beschreibung: "Anzahl der Fehler", Zugriff: "R", Typ: "char[2]", count: 5, Variable: "v01300", Bemerkung: "R: Anzahl der Bitcodierten Fehler aus V01303", Min: 0, Max: 32 },
    v01301: { Beschreibung: "Anzahl der Warnungen", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v01301", Bemerkung: "R: Anzahl der Bitcodierten Warnungen aus V01304", Min: 0, Max: 8 },
    v01302: { Beschreibung: "Anzahl der Infos", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v01302", Bemerkung: "R: Anzahl der Bitcodierten Infos aus V01305", Min: 0, Max: 8 },
    v01303: {
        Beschreibung: "Fehler",
        Zugriff: "R",
        Typ: "char[32]",
        count: 20,
        Variable: "v01303",
        Bemerkung: 'R: Fehler als String (siehe Tabelle "codierung") Beachte: V01123 - V01125',
        Min: null,
        Max: null,
    },
    v01304: {
        Beschreibung: "Warnungen",
        Zugriff: "R",
        Typ: "char[8]",
        count: 8,
        Variable: "v01304",
        Bemerkung: 'R: Warnungen als String (siehe Tabelle "codierung") Beachte: V01123 - V01125',
        Min: null,
        Max: null,
    },
    v01305: {
        Beschreibung: "Infos",
        Zugriff: "R",
        Typ: "char[8]",
        count: 8,
        Variable: "v01305",
        Bemerkung: 'R: Infos als String (siehe Tabelle "codierung") Beachte: V01123 - V01125',
        Min: null,
        Max: null,
    },
    v01306: { Beschreibung: "Statusflags", Zugriff: "R", Typ: "char[32]", count: 20, Variable: "v01306", Bemerkung: 'R: Sysflags als String (siehe Tabelle "codierung")', Min: null, Max: null },
    v02020: { Beschreibung: "KWL-FTF Konfig 1", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02020", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02021: { Beschreibung: "KWL-FTF Konfig 2", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02021", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02022: { Beschreibung: "KWL-FTF Konfig 3", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02022", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02023: { Beschreibung: "KWL-FTF Konfig 4", Zugriff: "R", Typ: "char[1]", count: 9, Variable: "v02023", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02024: { Beschreibung: "KWL-FTF Konfig 5", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02024", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02025: { Beschreibung: "KWL-FTF Konfig 6", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02025", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02026: { Beschreibung: "KWL-FTF Konfig 7", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02026", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02027: { Beschreibung: "KWL-FTF Konfig 8", Zugriff: "R", Typ: "char[1]", count: 5, Variable: "v02027", Bemerkung: "R: 0 = Kein Sensor, 1 = Sensor installiert", Min: 0, Max: 1 },
    v02013: {
        Beschreibung: "Global.ManualWeb- Update",
        Zugriff: "RW",
        Typ: "char[1]",
        count: 5,
        Variable: "v02013",
        Bemerkung: "RW: 1 = Manuelles Update der Daten (Profil 8: XGP, XWP, Firm- ware, SD-Files wird gestartet) 0 = Download nicht gesetartet oder abgeschlossen",
        Min: 1,
        Max: 1,
    },
    v02014: { Beschreibung: "PortalGlobals.Error- ForWeb", Zugriff: "R", Typ: "char[3]", count: 6, Variable: "v02014", Bemerkung: "R: Immer der Letzte Fehler der aufgetreten ist.", Min: 1, Max: 255 },
    v02015: { Beschreibung: "Fehler Löschen", Zugriff: "W", Typ: "char[1]", count: 5, Variable: "v02015", Bemerkung: "W: 1 = Fehler wird zurück gesetzt (PortalGlobals.ErrorForWeb)", Min: 1, Max: 1 },
    v00021: { Beschreibung: "kwl_be_aktiviert", Variable: "v00021", Bemerkung: "KWL-BE aktiviert ", Zugriff: "RW", Min: 0, Max: 1 },
    v01001: { Beschreibung: "dhcp_verwenden", Variable: "v01001", Bemerkung: "DHCP verwenden ", Zugriff: "RW", Min: 0, Max: 1 },
    v01002: { Beschreibung: "ip_adresse", Variable: "v01002", Bemerkung: "IP-Adresse W: 0 < strlen < 21", Zugriff: "RW" },
    v01003: { Beschreibung: "subnetzmaske", Variable: "v01003", Bemerkung: "Subnetzmaske W: 0 < strlen < 21", Zugriff: "RW" },
    v01004: { Beschreibung: "standard_gateway", Variable: "v01004", Bemerkung: "Standard Gateway W: 0 < strlen < 21", Zugriff: "RW" },
    v01005: { Beschreibung: "standard_dns", Variable: "v01005", Bemerkung: "Standard DNS W: 0 < strlen < 21", Zugriff: "RW" },
    v01006: { Beschreibung: "fallback_dns", Variable: "v01006", Bemerkung: "Fallback DNS W: 0 < strlen < 21", Zugriff: "RW" },
    v01007: { Beschreibung: "hostname", Variable: "v01007", Bemerkung: "Hostname W: 0 < strlen < 31", Zugriff: "RW" },
    v01200: { Beschreibung: "modbus_aktiviert", Variable: "v01200", Bemerkung: "Modbus Aktiviert ", Zugriff: "RW", Min: 0, Max: 1 },
    v02115: { Beschreibung: "passive_aussenluftkuehlung", Variable: "v02115", Bemerkung: "Passive Außenluftkühlung ", Zugriff: "RW", Min: 0, Max: 1 },
    v02116: { Beschreibung: "betriebsart_auto_immer_um_0_uhr_aktivieren", Variable: "v02116", Bemerkung: "Betriebsart Auto immer um 0 Uhr aktivieren ", Zugriff: "RW", Min: 0, Max: 1 },
    v02117: { Beschreibung: "aktuelle_leistung_vorheizung", Variable: "v02117", Bemerkung: "Aktuelle Leistung Vorheizung ", Zugriff: "R", Min: 0, Max: 100 },
    v02118: { Beschreibung: "aktuelle_leistung_nachheizung", Variable: "v02118", Bemerkung: "Aktuelle Leistung Nachheizung ", Zugriff: "R", Min: 0, Max: 100 },
    v02120: { Beschreibung: "bypass_aktivieren_im_zeitraum_vom_tag", Variable: "v02120", Bemerkung: "Bypass aktivieren im Zeitraum vom Tag ", Zugriff: "RW", Min: 1, Max: 31 },
    v02121: { Beschreibung: "bypass_aktivieren_im_zeitraum_von_monat", Variable: "v02121", Bemerkung: "Bypass aktivieren im Zeitraum von Monat ", Zugriff: "RW", Min: 1, Max: 12 },
    v02122: { Beschreibung: "nachheizungsprofil_aktivieren_vom_tag", Variable: "v02122", Bemerkung: "Nachheizungsprofil aktivieren vom Tag ", Zugriff: "RW", Min: 1, Max: 31 },
    v02123: { Beschreibung: "nachheizungsprofil_aktivieren_vom_monat", Variable: "v02123", Bemerkung: "Nachheizungsprofil aktivieren vom Monat ", Zugriff: "RW", Min: 1, Max: 12 },
    v02128: { Beschreibung: "bypass_aktivieren_im_zeitraum_bis_tag", Variable: "v02128", Bemerkung: "Bypass aktivieren im Zeitraum bis Tag ", Zugriff: "RW", Min: 1, Max: 31 },
    v02129: { Beschreibung: "bypass_aktivieren_im_zeitraum_bis_monat", Variable: "v02129", Bemerkung: "Bypass aktivieren im Zeitraum bis Monat ", Zugriff: "RW", Min: 1, Max: 12 },
    v02130: { Beschreibung: "nachheizungsprofil_aktivieren_bis_tag", Variable: "v02130", Bemerkung: "Nachheizungsprofil aktivieren bis Tag ", Zugriff: "RW", Min: 1, Max: 31 },
    v02131: { Beschreibung: "nachheizungsprofil_aktivieren_bis_monat", Variable: "v02131", Bemerkung: "Nachheizungsprofil aktivieren bis Monat ", Zugriff: "RW", Min: 1, Max: 12 },
    v02136: { Beschreibung: "interne_feuchtesteuerung_abluft", Variable: "v02136", Bemerkung: "Interne Feuchtesteuerung Abluft ", Zugriff: "R", Min: 0, Max: 100 },
    v02142: { Beschreibung: "interne_feuchtesteuerung_betriebsart", Variable: "v02142", Bemerkung: "Interne Feuchtesteuerung Betriebsart ", Zugriff: "RW", Min: 0, Max: 1 },
    v02143: { Beschreibung: "interne_feuchtesteuerung_stoppzeit", Variable: "v02143", Bemerkung: "Interne Feuchtesteuerung Stoppzeit ", Zugriff: "RW", Min: 0, Max: 24 },
    v02145: { Beschreibung: "interne_feuchtesteuerung_januar_maerz", Variable: "v02145", Bemerkung: "Interne Feuchtesteuerung Januar-März ", Zugriff: "RW", Min: 0, Max: 100 },
    v02146: { Beschreibung: "interne_feuchtesteuerung_april_juni", Variable: "v02146", Bemerkung: "Interne Feuchtesteuerung April-Juni ", Zugriff: "RW", Min: 0, Max: 100 },
    v02147: { Beschreibung: "interne_feuchtesteuerung_juli_september", Variable: "v02147", Bemerkung: "Interne Feuchtesteuerung Juli-September ", Zugriff: "RW", Min: 0, Max: 100 },
    v02148: { Beschreibung: "interne_feuchtesteuerung_oktober_dezember", Variable: "v02148", Bemerkung: "Interne Feuchtesteuerung Oktober-Dezember ", Zugriff: "RW", Min: 0, Max: 100 },
    v02149: { Beschreibung: "ruhemodus_fuer_fuehlerregelung_von", Variable: "v02149", Bemerkung: "Ruhemodus für Fühlerregelung von R: Format: hh:mm W: Format: hh:mm", Zugriff: "RW" },
    v02150: { Beschreibung: "ruhemodus_fuer_fuehlerregelung_bis", Variable: "v02150", Bemerkung: "Ruhemodus für Fühlerregelung bis R: Format: hh:mm W: Format: hh:mm", Zugriff: "RW" },
    v02119: { Beschreibung: "bypass_offen", Variable: "v02119", Bemerkung: "Bypassklappe geöffnet (Abluft ohne Wärmetauscher) ", Zugriff: "R", Min: 0, Max: 1 },
};
