/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "helios adapter settings": {
        en: "Adapter settings for helios",
        de: "Adaptereinstellungen für helios",
        ru: "Настройки адаптера для helios",
        pt: "Configurações do adaptador para helios",
        nl: "Adapterinstellingen voor helios",
        fr: "Paramètres d'adaptateur pour helios",
        it: "Impostazioni dell'adattatore per helios",
        es: "Ajustes del adaptador para helios",
        pl: "Ustawienia adaptera dla helios",
        "zh-cn": "helios的适配器设置",
    },

    Password: {
        en: "Password",
        de: "Passwort",
        ru: "Пароль",
        pt: "Senha",
        nl: "Wachtwoord",
        fr: "Mot de passe",
        it: "Parola d'ordine",
        es: "Contraseña",
        pl: "Hasło",
        "zh-cn": "密码",
    },
    IP: {
        en: "IP",
        de: "IP",
        ru: "IP",
        pt: "IP",
        nl: "IK P",
        fr: "IP",
        it: "IP",
        es: "IP",
        pl: "IP",
        "zh-cn": "知识产权",
    },
    "Interval in seconds": {
        en: "Interval in seconds",
        de: "Intervall in Sekunden",
        ru: "Интервал в секундах",
        pt: "Intervalo em segundos",
        nl: "Interval in seconden",
        fr: "Intervalle en secondes",
        it: "Intervallo in secondi",
        es: "Intervalo en segundos",
        pl: "Interwał w sekundach",
        "zh-cn": "以秒为单位的间隔",
    },
    "XML pages to be updated in the interval (1-17)": {
        en: "XML pages to be updated in the interval (1-17)",
        de: "XML Seiten die im Intervall geupdateten werden sollen (1-17)",
        ru: "Страницы XML будут обновляться в интервале (1-17)",
        pt: "Páginas XML a serem atualizadas no intervalo (1-17)",
        nl: "XML-pagina's die in het interval moeten worden bijgewerkt (1-17)",
        fr: "Pages XML à mettre à jour dans l'intervalle (1-17)",
        it: "Pagine XML da aggiornare nell'intervallo (1-17)",
        es: "Páginas XML que se actualizarán en el intervalo (1-17)",
        pl: "Strony XML do aktualizacji w przedziale (1-17)",
        "zh-cn": "间隔（1-17）更新的XML页面",
    },
};
